using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class QuestCreator : MonoBehaviour
{
    [Header("Quest source")]
    [SerializeField] private bool _useAutoGeneratedQuests = true;
    [SerializeField] private QuestGenerationSettings _questGenerationSettings;
    [SerializeField] private List<QuestData> _quests = new();

    [Header("Services")]
    [SerializeField] private VisitorService _visitorService;
    [SerializeField] private DevicePurchase _devicePurchase;
    [SerializeField] private CoinsData _coinsData;

    [Header("UI")]
    [SerializeField] private GameObject _questPrefab;
    [SerializeField] private Transform _content;

    private readonly List<Quest> _allQuestsTypes = new();
    private readonly List<GameObject> _allQuestObjects = new();
    private readonly List<int> _pendingRewardQuestIndexes = new();

    private List<QuestData> _runtimeQuests;

    private int _activeQuestIndex;
    private Quest _activeQuest;
    private QuestUI _activeQuestUI;

    private bool _isInitialized;
    private bool _isStartingNextQuest;

    private bool _hasPendingRestore;
    private QuestSaveData _pendingRestoreData;

    public int ActiveQuestIndex => _activeQuestIndex;
    public int ActiveQuestProgress => _activeQuest != null ? _activeQuest.CurrentProgress : 0;
    public bool IsActiveQuestCompleted => _activeQuest != null && _activeQuest.IsCompleted;

    private void Start()
    {
        Initialize();

        if (_hasPendingRestore)
        {
            ApplySave(_pendingRestoreData);
            _hasPendingRestore = false;
            return;
        }

        StartQuestAt(0, 0, false);
    }

    public QuestSaveData CaptureSave()
    {
        return new QuestSaveData
        {
            HasQuestSave = true,
            ActiveQuestIndex = _activeQuestIndex,
            CurrentProgress = ActiveQuestProgress,
            IsCompleted = false,
            PendingRewardQuestIndexes = new List<int>(_pendingRewardQuestIndexes)
        };
    }

    public void RestoreSave(QuestSaveData data)
    {
        if (data == null || data.HasQuestSave == false)
            return;

        if (!_isInitialized)
        {
            _pendingRestoreData = data;
            _hasPendingRestore = true;
            return;
        }

        ApplySave(data);
    }

    private void ApplySave(QuestSaveData data)
    {
        if (_runtimeQuests == null || _runtimeQuests.Count == 0)
            return;

        CleanupActiveQuest();
        HideAllQuestObjects();

        _pendingRewardQuestIndexes.Clear();

        if (data.PendingRewardQuestIndexes != null)
        {
            for (int i = 0; i < data.PendingRewardQuestIndexes.Count; i++)
                AddPendingRewardUI(data.PendingRewardQuestIndexes[i], false);
        }

        // Поддержка старого сейва: если раньше активный квест был выполнен, но награда не забрана,
        // переносим его в pending и запускаем следующий.
        int activeIndex = Mathf.Clamp(data.ActiveQuestIndex, 0, _runtimeQuests.Count);

        if (data.IsCompleted && activeIndex < _runtimeQuests.Count)
        {
            AddPendingRewardUI(activeIndex, false);
            activeIndex++;
        }

        if (activeIndex >= _runtimeQuests.Count)
        {
            CompleteAllActiveQuests();
            return;
        }

        StartQuestAt(activeIndex, data.CurrentProgress, false);
    }

    private void Initialize()
    {
        _runtimeQuests = _useAutoGeneratedQuests
            ? QuestAutoList.Create(_questGenerationSettings)
            : _quests;

        _allQuestsTypes.Clear();
        _allQuestsTypes.Add(new VisitorServiceQuest(_visitorService, _coinsData));
        _allQuestsTypes.Add(new BuyDeviceQuest(_devicePurchase, _coinsData));

        CreateQuestObjects();
        _isInitialized = true;
    }

    private void CreateQuestObjects()
    {
        foreach (GameObject oldObject in _allQuestObjects)
        {
            if (oldObject != null)
                Destroy(oldObject);
        }

        _allQuestObjects.Clear();

        foreach (QuestData quest in _runtimeQuests)
        {
            GameObject go = Instantiate(_questPrefab, _content);

            if (go.TryGetComponent(out QuestUI questUI))
                questUI.Init(quest);

            go.SetActive(false);
            _allQuestObjects.Add(go);
        }
    }

    private void StartQuestAt(int index, int progress, bool isCompleted)
    {
        _isStartingNextQuest = false;

        if (_runtimeQuests == null || index >= _runtimeQuests.Count)
        {
            CompleteAllActiveQuests();
            return;
        }

        CleanupActiveQuest();

        _activeQuestIndex = index;

        QuestData questData = _runtimeQuests[_activeQuestIndex];
        Quest quest = GetQuestByType(questData.Type);

        if (quest == null)
        {
            Debug.LogError($"Не найден обработчик для квеста типа: {questData.Type}");
            return;
        }

        _activeQuest = quest;
        _activeQuest.ForceUnsubscribe();
        _activeQuest.OnCompleted += OnActiveQuestCompleted;

        GameObject questObject = _allQuestObjects[_activeQuestIndex];
        questObject.SetActive(true);

        if (!questObject.TryGetComponent(out _activeQuestUI))
        {
            Debug.LogError("На префабе квеста нет QuestUI.");
            return;
        }

        _activeQuestUI.ActivateTracking(_activeQuest, questData, _activeQuestIndex, ClaimQuestReward);

        if (progress > 0 || isCompleted)
            _activeQuest.Restore(questData, progress, isCompleted);
        else
            _activeQuest.Activate(questData);
    }

    private void OnActiveQuestCompleted()
    {
        if (_isStartingNextQuest)
            return;

        _isStartingNextQuest = true;

        int completedIndex = _activeQuestIndex;

        if (_activeQuestUI != null)
            _activeQuestUI.MarkRewardAvailable(true);

        if (!_pendingRewardQuestIndexes.Contains(completedIndex))
            _pendingRewardQuestIndexes.Add(completedIndex);

        if (_activeQuest != null)
        {
            _activeQuest.OnCompleted -= OnActiveQuestCompleted;
            _activeQuest.ForceUnsubscribe();
        }

        _activeQuest = null;
        _activeQuestUI = null;
        _activeQuestIndex = completedIndex + 1;

        StartCoroutine(StartNextQuestNextFrame(_activeQuestIndex));
    }

    private IEnumerator StartNextQuestNextFrame(int index)
    {
        yield return null;
        StartQuestAt(index, 0, false);
    }

    private void ClaimQuestReward(int questIndex)
    {
        _pendingRewardQuestIndexes.Remove(questIndex);

        if (questIndex >= 0 && questIndex < _allQuestObjects.Count)
            _allQuestObjects[questIndex].SetActive(false);
    }

    private void AddPendingRewardUI(int questIndex, bool playPulse)
    {
        if (questIndex < 0 || questIndex >= _runtimeQuests.Count)
            return;

        if (!_pendingRewardQuestIndexes.Contains(questIndex))
            _pendingRewardQuestIndexes.Add(questIndex);

        QuestData questData = _runtimeQuests[questIndex];
        Quest questHandler = GetQuestByType(questData.Type);

        if (questHandler == null)
            return;

        GameObject questObject = _allQuestObjects[questIndex];
        questObject.SetActive(true);

        if (questObject.TryGetComponent(out QuestUI questUI))
        {
            questUI.ShowPendingReward(questData, questHandler.ResourceData, questIndex, ClaimQuestReward);

            if (playPulse)
                questUI.MarkRewardAvailable(true);
        }
    }

    private void CleanupActiveQuest()
    {
        if (_activeQuest != null)
        {
            _activeQuest.OnCompleted -= OnActiveQuestCompleted;
            _activeQuest.ForceUnsubscribe();
        }

        _activeQuest = null;
        _activeQuestUI = null;
    }

    private void CompleteAllActiveQuests()
    {
        CleanupActiveQuest();

        _activeQuestIndex = _runtimeQuests != null ? _runtimeQuests.Count : 0;
        _isStartingNextQuest = false;

        Debug.Log("Активные квесты закончились. Незабранные награды, если есть, остаются в UI.");
    }

    private void HideAllQuestObjects()
    {
        foreach (GameObject questObject in _allQuestObjects)
        {
            if (questObject != null)
                questObject.SetActive(false);
        }
    }

    private Quest GetQuestByType(QuestType type)
    {
        for (int i = 0; i < _allQuestsTypes.Count; i++)
        {
            if (_allQuestsTypes[i].Type == type)
                return _allQuestsTypes[i];
        }

        return null;
    }
}
